"env": "local" # local, dev, prod
"storage_path":
  "db_type": "postgres"
  "db_user": "userL0"
  "db_user_password": "123456"
  "db_port": "0.0.0.0:5432"
  "db_name": "postgres"
#  "postgres://userL0:123456@0.0.0.0:5432/postgres"
"http_server":
  "address": "localhost:8085"
  "timeout": 4s
  "idle_timeout": 60s
